version: '3.7'
services:
  aosofront:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
     - "4200"
    tty: true
    restart : always
    volumes:
      - ./:/var/www
    depends_on:
     - reversproxyfront
    networks:
     - some-net

   #nginx server 
  reversproxyfront:
    build:
      context : .
      dockerfile : nginx/Dockerfile
    volumes:
      - ./:/var/www
     # - "./nginx.conf:/etc/nginx/nginx.conf:ro" #ro:read only

    ports:
      - "4004:80"
    tty: true
    restart : always
    networks:
      - some-net
networks:
   some-net:
     driver: bridge
#   #  external: true