# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  aosofront:
    build:
      context: ./AosoFront
      dockerfile: Dockerfile
    ports:
     - "4200"
    tty: true
    restart : always
    volumes:
      - '.:/app'
      - ./:/var/www
    depends_on:
     - reversproxy
   
   #nginx server 
  reversproxy:
    build:
      context : ./
      dockerfile : nginx/Dockerfile
    volumes:
      - ./:/var/www
     # - "./nginx.conf:/etc/nginx/nginx.conf:ro" #ro:read only
    ports: 
      - "4002:80"
    tty: true
    restart : always
     
   
  